version: "2"
services:
  tmp:
    image: busybox
    command: chmod -R 0777 /tmp/docker
    volumes:
      - /tmp/docker

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./env/mysql:/var/lib/mysql
      - ./env/mysqld:/var/run/mysqld

  nginx:
    image: nginx:alpine
    ports: 
      - "8080:80"
    volumes:
      - ./env/www/storage:/var/www/storage
      - ./env/www/storage/bootstrap:/var/www/storage/bootstrap
      - ./env/www:/var/www:ro
      - ./env/nginx:/etc/nginx/:ro
    depends_on:
      - tmp
    volumes_from:
      - tmp

  php:
    build:
      context: ./dockerfiles/
      dockerfile: php7-fpm-pdo-mysql
    volumes:
      - './env/php-fpm.d:/usr/local/etc/php-fpm.d/:ro'
      - './env/php:/usr/local/etc/php:ro'
    volumes_from:
      - tmp
      - nginx
      - db
    depends_on:
      - db
    working_dir: '/var/www'
    command: > 
      sh -c 'sleep 15 && echo "Start php image" && php -m && php /var/www/artisan migrate --seed && php-fpm -F'
